name: aes_crypt
description: Dart encryption library for encrypting/decrypting files, plain text and binary data in AES Crypt file format.
version: 0.1.1
homepage: https://github.com/alexgoussev/aes_crypt
repository: https://github.com/alexgoussev/aes_crypt

environment:
  sdk: '>=2.16.2 <3.0.0'

# dependencies:

dev_dependencies:
  lints: 
  test: ^1.20.2
